rootProject.name = "rt4-client"

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        maven { url 'https://jitpack.io' }
        flatDir {
            dirs 'lib'
        }
    }
}

include(
    "deob-annotations",
    "signlink",
    "client",
    "playground"
)

startParameter.excludedTaskNames << ':playground:run'
