package rt4.amilious.guide;

/**
 * 2009-efficient route. QUEST rows award XP; TRAIN rows fire only when the
 * next quest still needs the level.
 *
 * Skill ids: see ProgressGuide.SKILL_NAMES
 * optionalQuest = skip if not implemented on this world.
 */
public final class OptimalRoute {

    private static final int ATK = 0, DEF = 1, STR = 2, HP = 3, RNG = 4, PRAY = 5, MAG = 6;
    private static final int COOK = 7, WC = 8, FLET = 9, FISH = 10, FM = 11, CRAFT = 12, SMTH = 13;
    private static final int MINE = 14, HERB = 15, AGIL = 16, THIE = 17, SLAY = 18, FARM = 19;
    private static final int RC = 20, HUNT = 21, CON = 22, SUMM = 23;

    private static final String[] NONE = new String[0];

    public static final GuideStep[] STEPS = {

            GuideStep.quest("cook", "Cook's Assistant", "Lumbridge Castle cook",
                    "1 QP, 300 Cook XP", NONE, null, new int[][]{{COOK, 300}}),
            GuideStep.quest("sheep", "Sheep Shearer", "Fred the Farmer north of Lumbridge",
                    "1 QP, 130 Craft XP", NONE, null, new int[][]{{CRAFT, 130}}),
            GuideStep.quest("restless", "The Restless Ghost", "Father Aereck, Lumbridge church",
                    "1 QP, 1125 Prayer — do this before burying bones", NONE, null, new int[][]{{PRAY, 1125}}),
            GuideStep.quest("rune-myst", "Rune Mysteries", "Duke Horacio, Lumbridge",
                    "Unlocks essence + lamps on RC", NONE, null, null),
            GuideStep.quest("imp", "Imp Catcher", "Wizard Mizgog, Wizards' Tower",
                    "1 QP, 875 Magic", NONE, null, new int[][]{{MAG, 875}}),
            GuideStep.quest("witch-pot", "Witch's Potion", "Hetty, Rimmington",
                    "1 QP, 325 Magic", NONE, null, new int[][]{{MAG, 325}}),
            GuideStep.quest("doric", "Doric's Quest", "Doric north of Falador",
                    "1 QP, 1300 Mining", NONE, new int[][]{{MINE, 1}}, new int[][]{{MINE, 1300}}),
            GuideStep.quest("goblin", "Goblin Diplomacy", "Generals in Goblin Village",
                    "5 QP", NONE, null, null),
            GuideStep.quest("romeo", "Romeo & Juliet", "Romeo in Varrock square",
                    "5 QP", NONE, null, null),
            GuideStep.quest("ernest", "Ernest the Chicken", "Veronica, Draynor Manor",
                    "4 QP", NONE, null, null),
            GuideStep.quest("ali", "Prince Ali Rescue", "Hassan, Al Kharid palace",
                    "3 QP — needed for later desert", NONE, null, null),
            GuideStep.quest("bkf", "Black Knights' Fortress", "Sir Amik Varze, Falador",
                    "3 QP — needs 12 QP", NONE, null, null),
            GuideStep.quest("demon", "Demon Slayer", "Gypsy Aris, Varrock",
                    "Silverlight", NONE, null, null),
            GuideStep.train("mine-10", MINE, 10, "Iron south-east Varrock or Rimmington"),
            GuideStep.quest("knight", "The Knight's Sword", "Squire, White Knights' Castle",
                    "Huge Smithing XP", NONE, new int[][]{{MINE, 10}}, new int[][]{{SMTH, 12725}}),
            GuideStep.quest("pirate", "Pirate's Treasure", "Redbeard Frank, Port Sarim",
                    "2 QP, Karamja access via ship", NONE, null, null),
            GuideStep.quest("arrav", "Shield of Arrav", "Reldo, Varrock palace library",
                    "1 QP — Phoenix or Black Arm", NONE, null, null),
            GuideStep.quest("vamp", "Vampire Slayer", "Morgan, Draynor Village",
                    "4825 Attack XP", NONE, null, new int[][]{{ATK, 4825}}),
            GuideStep.quest("dragon", "Dragon Slayer", "Guildmaster, Champions' Guild",
                    "32 QP req, rune plate, anti-dragon shield",
                    new String[]{"Quest points 32"}, null, new int[][]{{STR, 18650}, {DEF, 18650}}),

            GuideStep.quest("druidic", "Druidic Ritual", "Kaqemeex, Taverley",
                    "Unlocks Herblore + lamps on Herb", NONE, null, new int[][]{{HERB, 250}}),
            GuideStep.optionalQuest("wolf-whistle", "Wolf Whistle", "Pikkupstix, Taverley",
                    "Summoning tutorial + 276 Summoning XP", NONE, null, new int[][]{{SUMM, 276}}),
            GuideStep.quest("witch-house", "Witch's House", "Boy in Taverley",
                    "6325 Hitpoints XP", NONE, null, new int[][]{{HP, 6325}}),
            GuideStep.quest("waterfall", "Waterfall Quest", "Almera, Baxtorian Falls",
                    "13750 Attack + Strength — do this before any combat grind",
                    NONE, null, new int[][]{{ATK, 13750}, {STR, 13750}}),
            GuideStep.quest("tree-gnome", "Tree Gnome Village", "King Bolren, Maze",
                    "11450 Attack + spirit tree", NONE, null, new int[][]{{ATK, 11450}}),
            GuideStep.quest("fight-arena", "Fight Arena", "Lady Servil, south of Ardougne",
                    "12175 Attack + 2175 Thieving", NONE, null, new int[][]{{ATK, 12175}, {THIE, 2175}}),
            GuideStep.train("agil-25", AGIL, 25, "Draynor rooftop or Gnome stronghold"),
            GuideStep.quest("grand-tree", "The Grand Tree", "King Narnode, Grand Tree",
                    "Gliders + 18400 Attack + 7900 Agility",
                    NONE, new int[][]{{AGIL, 25}}, new int[][]{{AGIL, 7900}, {ATK, 18400}, {MAG, 2150}}),
            GuideStep.quest("gertrude", "Gertrude's Cat", "Gertrude west of Varrock",
                    "Pet cat — needed for Icthlarin", NONE, null, new int[][]{{COOK, 1525}}),
            GuideStep.quest("plague", "Plague City", "Edmond, north Ardougne",
                    "Ardougne teleport", NONE, null, null),
            GuideStep.quest("biohazard", "Biohazard", "Elena, north Ardougne",
                    "Combat potion shop / West Ardougne",
                    new String[]{"Plague City"}, null, null),
            GuideStep.quest("priest", "Priest in Peril", "King Roald, Varrock palace",
                    "Unlocks Morytania", NONE, null, new int[][]{{PRAY, 1406}}),
            GuideStep.train("craft-20", CRAFT, 20, "Leather or jewellery — Nature Spirit needs 18"),
            GuideStep.quest("nature", "Nature Spirit", "Drezel after Priest in Peril",
                    "Silver sickle, Mort Myre",
                    new String[]{"Priest in Peril", "The Restless Ghost"}, new int[][]{{CRAFT, 18}}, null),

            GuideStep.quest("obs", "Observatory Quest", "Observatory professor",
                    "Craft + weapon XP", NONE, new int[][]{{CRAFT, 10}}, null),
            GuideStep.quest("ew1", "Elemental Workshop I", "Bookcase south-west of Seers bank",
                    "5000 Craft + 5000 Smith, elemental shield",
                    NONE, new int[][]{{SMTH, 20}, {CRAFT, 20}}, new int[][]{{CRAFT, 5000}, {SMTH, 5000}}),
            GuideStep.quest("clock", "Clock Tower", "Brother Kojo, Clock Tower",
                    "1 QP, easy coins", NONE, null, null),
            GuideStep.quest("monk", "Monk's Friend", "Brother Omad, Ardougne monastery",
                    "2000 Woodcutting", NONE, null, new int[][]{{WC, 2000}}),
            GuideStep.quest("hazeel", "Hazeel Cult", "Jones or Alomone cave, Ardougne",
                    "1500 Thieving", NONE, null, new int[][]{{THIE, 1500}}),
            GuideStep.quest("sheep-herd", "Sheep Herder", "Councillor Halgrive, Ardougne",
                    "4 QP, easy cash", NONE, null, null),
            GuideStep.quest("dwarf-cannon", "Dwarf Cannon", "Captain Lawgof, north of Coal Trucks",
                    "Dwarf multicannon", NONE, null, new int[][]{{CRAFT, 750}}),
            GuideStep.train("fish-10", FISH, 10, "Shrimp / bait fish — Fishing Contest"),
            GuideStep.quest("fishing-contest", "Fishing Contest", "Mountain dwarf, White Wolf Pass",
                    "Fishing Guild access later", NONE, new int[][]{{FISH, 10}}, new int[][]{{FISH, 2437}}),
            GuideStep.optionalQuest("sea-slug", "Sea Slug", "Caroline, Witchaven",
                    "7175 Fishing XP", NONE, new int[][]{{FM, 30}}, new int[][]{{FISH, 7175}}),
            GuideStep.train("pray-31", PRAY, 31, "Ecto / gilded / dragon bones — Scorpion Catcher"),
            GuideStep.quest("scorpion", "Scorpion Catcher", "Thormac, Sorcerer's Tower",
                    "6625 Strength", NONE, new int[][]{{PRAY, 31}}, new int[][]{{STR, 6625}}),
            GuideStep.train("rng-40", RNG, 40, "Cows / hill giants / quest lamps — Ikov"),
            GuideStep.train("thiev-42", THIE, 42, "Ardougne cake stall — Ikov picklock"),
            GuideStep.quest("ikov", "Temple of Ikov", "Lucien, Flying Horse Inn, Ardougne",
                    "Boots of lightness, ranged XP",
                    NONE, new int[][]{{THIE, 42}, {RNG, 40}}, new int[][]{{RNG, 10500}}),

            GuideStep.quest("tribal", "Tribal Totem", "Horacio, Ardougne",
                    "1775 Thieving", NONE, new int[][]{{THIE, 21}}, new int[][]{{THIE, 1775}}),
            GuideStep.quest("jungle", "Jungle Potion", "Trufitus, Tai Bwo Wannai",
                    "Herblore XP, opens Tai Bwo",
                    new String[]{"Druidic Ritual"}, new int[][]{{HERB, 3}}, new int[][]{{HERB, 775}}),
            GuideStep.quest("digsite", "The Dig Site", "Examiner, Exam Centre",
                    "Needed for Desert Treasure",
                    NONE, new int[][]{{THIE, 25}, {AGIL, 10}, {HERB, 10}}, new int[][]{{MINE, 15300}, {HERB, 2000}}),
            GuideStep.quest("murder", "Murder Mystery", "Puncheons, Sinclair Mansion",
                    "3 QP, 1406 Crafting", NONE, null, new int[][]{{CRAFT, 1406}}),
            GuideStep.quest("recruit", "Recruitment Drive", "Sir Tiffy, Falador park",
                    "Initiate armour",
                    new String[]{"Black Knights' Fortress", "Druidic Ritual"}, null, null),
            GuideStep.quest("golem", "The Golem", "Clay golem, Uzer",
                    "1000 Craft + 1000 Magic, desert unlock",
                    NONE, new int[][]{{CRAFT, 20}, {THIE, 25}}, new int[][]{{CRAFT, 1000}, {MAG, 1000}}),
            GuideStep.optionalQuest("sots", "Shadow of the Storm", "Dark wizard, ruins north of Al Kharid",
                    "10000 XP lamp (combat typical)",
                    new String[]{"Demon Slayer", "The Golem"}, null, null),

            GuideStep.train("craft-31", CRAFT, 31, "Gold jewellery — Lost City"),
            GuideStep.train("wc-36", WC, 36, "Oaks / willows — Lost City"),
            GuideStep.quest("lost-city", "Lost City", "Warrior, Lumbridge swamp",
                    "Zanaris + dragon dagger/long + cosmics",
                    NONE, new int[][]{{CRAFT, 31}, {WC, 36}}, null),
            GuideStep.quest("fairytale-1", "Fairytale I - Growing Pains", "Martin the Farmer, Draynor",
                    "Magic secateurs",
                    new String[]{"Lost City", "Nature Spirit"}, null, new int[][]{{FARM, 3500}, {ATK, 2000}, {MAG, 1000}}),
            GuideStep.optionalQuest("fairytale-2", "Fairytale II - Cure a Queen", "Fairy Nuff, Zanaris",
                    "Start only — fairy rings unlock mid-quest",
                    new String[]{"Fairytale I - Growing Pains"}, new int[][]{{THIE, 40}, {FARM, 49}, {HERB, 57}}, null),
            GuideStep.quest("ghosts", "Ghosts Ahoy", "Necrovarus / Velorina, Port Phasmatys",
                    "Ectophial",
                    new String[]{"Priest in Peril", "The Restless Ghost"}, new int[][]{{AGIL, 25}, {COOK, 20}}, null),
            GuideStep.quest("animal-mag", "Animal Magnetism", "Ava, Draynor Manor",
                    "Ava's accumulator",
                    new String[]{"The Restless Ghost", "Ernest the Chicken", "Priest in Peril"},
                    new int[][]{{SLAY, 18}, {CRAFT, 19}, {RNG, 30}, {WC, 35}}, null),
            GuideStep.optionalQuest("tog", "Tears of Guthix", "Juna, Tears cave (Lumbridge swamp)",
                    "Weekly best-skill lamp",
                    new String[]{"Lost City"}, new int[][]{{CRAFT, 20}, {FM, 49}, {MINE, 20}}, null),

            GuideStep.train("smith-40", SMTH, 40, "Iron/steel at Varrock or Blast Furnace later"),
            GuideStep.quest("tourist", "The Tourist Trap", "Irena, Shantay Pass",
                    "2x 4650 XP lamps (Smith/Agil typical)",
                    NONE, new int[][]{{FLET, 10}, {SMTH, 20}}, null),
            GuideStep.quest("shilo", "Shilo Village", "Mosol Rei, south Karamja",
                    "Shilo cart + gem rocks",
                    new String[]{"Jungle Potion"}, new int[][]{{CRAFT, 20}, {AGIL, 32}}, null),
            GuideStep.quest("watchtower", "Watchtower", "Watchtower wizard, Yanille",
                    "Watchtower teleport",
                    NONE, new int[][]{{MAG, 15}, {THIE, 15}, {AGIL, 25}, {HERB, 14}, {MINE, 40}}, null),

            GuideStep.quest("death-plat", "Death Plateau", "Denulth, Burthorpe",
                    "Climbing boots + 3000 Attack", NONE, null, new int[][]{{ATK, 3000}}),
            GuideStep.quest("troll-strong", "Troll Stronghold", "Denulth after Death Plateau",
                    "Law runes + 2x 10000 XP lamps",
                    new String[]{"Death Plateau"}, new int[][]{{AGIL, 15}}, null),
            GuideStep.quest("eadgar", "Eadgar's Ruse", "Eadgar, Trollheim",
                    "Trollheim teleport",
                    new String[]{"Druidic Ritual", "Troll Stronghold"}, new int[][]{{HERB, 31}, {AGIL, 44}}, null),
            GuideStep.quest("frem-trials", "The Fremennik Trials", "Brundt, Rellekka",
                    "Lyre teleports, Fremennik area",
                    NONE, new int[][]{{CRAFT, 40}, {WC, 40}, {FLET, 25}}, new int[][]{{AGIL, 2812}, {ATK, 2812}, {STR, 2812}, {HP, 2812}, {CRAFT, 2812}, {DEF, 2812}, {FISH, 2812}, {FM, 2812}, {THIE, 2812}, {WC, 2812}}),
            GuideStep.optionalQuest("frem-isles", "The Fremennik Isles", "Mord Gunnars, Rellekka dock",
                    "Helm of Neitiznot",
                    new String[]{"The Fremennik Trials"}, new int[][]{{CON, 20}, {CRAFT, 46}}, null),
            GuideStep.quest("horror", "Horror from the Deep", "Larrissa, Lighthouse",
                    "God books",
                    NONE, new int[][]{{AGIL, 35}}, null),
            GuideStep.quest("merlin", "Merlin's Crystal", "King Arthur, Camelot",
                    "Excalibur — required for Heroes' and Holy Grail", NONE, null, null),
            GuideStep.quest("holy-grail", "Holy Grail", "King Arthur, Camelot",
                    "11000 Prayer + 15300 Defence",
                    new String[]{"Merlin's Crystal"}, new int[][]{{ATK, 20}}, new int[][]{{PRAY, 11000}, {DEF, 15300}}),
            GuideStep.train("cook-53", COOK, 53, "Lobsters / wine — Heroes' Quest"),
            GuideStep.train("fish-53", FISH, 53, "Lobsters — Heroes' Quest"),
            GuideStep.quest("heroes", "Heroes' Quest", "Achietties, Heroes' Guild",
                    "Dragon mace/battleaxe, fountain of heroes",
                    new String[]{"Shield of Arrav", "Lost City", "Dragon Slayer", "Merlin's Crystal"},
                    new int[][]{{COOK, 53}, {FISH, 53}, {HERB, 25}, {MINE, 50}}, null),

            GuideStep.train("agil-50", AGIL, 50, "Wilderness course or Seers when diary allows"),
            GuideStep.quest("underground", "Underground Pass", "King Lathas, Ardougne castle",
                    "Iban's staff, path to Regicide",
                    new String[]{"Biohazard"}, new int[][]{{RNG, 25}}, new int[][]{{ATK, 3000}, {AGIL, 3000}}),
            GuideStep.quest("regicide", "Regicide", "King Lathas after Underground Pass",
                    "Tirannwn + crystal bow later",
                    new String[]{"Underground Pass"}, new int[][]{{AGIL, 56}, {CRAFT, 10}}, new int[][]{{AGIL, 13750}}),
            GuideStep.optionalQuest("roving", "Roving Elves", "Islwyn, Isafdar",
                    "Crystal bow/shield",
                    new String[]{"Regicide", "Waterfall Quest"}, new int[][]{{AGIL, 56}}, null),
            GuideStep.train("rng-30", RNG, 30, "Chompy / cannon — skip if already 40 from Ikov"),
            GuideStep.optionalQuest("chompy", "Big Chompy Bird Hunting", "Rantz, Feldip Hills",
                    "Chompy hunting, MEP I req",
                    NONE, new int[][]{{RNG, 30}, {COOK, 30}}, null),
            GuideStep.optionalQuest("mep1", "Mourning's End Part I", "Eluned / Arianwyn",
                    "Teleport crystal, Lletya",
                    new String[]{"Roving Elves", "Big Chompy Bird Hunting", "Sheep Herder"},
                    new int[][]{{THIE, 50}, {RNG, 60}}, null),
            GuideStep.optionalQuest("mep2", "Mourning's End Part II", "Arianwyn, Lletya",
                    "Death altar",
                    new String[]{"Mourning's End Part I"}, new int[][]{{AGIL, 60}, {THIE, 60}}, new int[][]{{AGIL, 20000}}),

            GuideStep.quest("ict", "Icthlarin's Little Helper", "Wanderer, Sophanem",
                    "Sophanem access",
                    new String[]{"Gertrude's Cat"}, null, new int[][]{{THIE, 4500}, {AGIL, 4000}, {PRAY, 4000}}),
            GuideStep.quest("contact", "Contact!", "Osman / Sophanem",
                    "Keris + bank in Sophanem",
                    new String[]{"Prince Ali Rescue", "Icthlarin's Little Helper"},
                    new int[][]{{THIE, 22}}, null),
            GuideStep.train("mag-50", MAG, 50, "Splash / alch / tasks — DT needs 50 Magic"),
            GuideStep.train("fm-50", FM, 50, "Willows"),
            GuideStep.train("mag-59", MAG, 59, "Alch / tasks — Family Crest"),
            GuideStep.quest("ikov-family", "Family Crest", "Dimintheis, Varrock",
                    "Gauntlets — family crest",
                    NONE, new int[][]{{CRAFT, 40}, {SMTH, 40}, {MAG, 59}, {MINE, 40}}, null),
            GuideStep.quest("dt", "Desert Treasure", "Archaeologist, Bedabin Camp",
                    "Ancient Magicks",
                    new String[]{"The Dig Site", "Temple of Ikov", "The Tourist Trap", "Troll Stronghold", "Priest in Peril", "Waterfall Quest"},
                    new int[][]{{SLAY, 10}, {FM, 50}, {MAG, 50}, {THIE, 53}}, null),

            GuideStep.quest("lost-tribe", "The Lost Tribe", "Sigmund / Reldo",
                    "Dorgeshuun mines",
                    new String[]{"Goblin Diplomacy", "Rune Mysteries"}, new int[][]{{AGIL, 13}, {MINE, 17}, {THIE, 13}}, null),
            GuideStep.quest("dtd", "Death to the Dorgeshuun", "Mistag / Dorgesh-Kaan",
                    "Dorgesh-Kaan city",
                    new String[]{"The Lost Tribe"}, new int[][]{{AGIL, 23}, {THIE, 23}}, null),

            GuideStep.quest("osf", "One Small Favour", "Yanni / Hamal / chain from Shilo",
                    "2x 10000 XP lamps — King's Ransom req",
                    new String[]{"Shilo Village", "Rune Mysteries"},
                    new int[][]{{AGIL, 36}, {CRAFT, 25}, {HERB, 18}, {SMTH, 30}}, null),
            GuideStep.quest("rfd-cook", "Recipe for Disaster", "Cook, Lumbridge — start the council",
                    "Start RFD; subquests as QP allows",
                    new String[]{"Cook's Assistant"}, null, null),
            GuideStep.optionalQuest("mm", "Monkey Madness", "King Narnode after Grand Tree + Tree Gnome Village",
                    "Dragon scimitar, Ape Atoll",
                    new String[]{"The Grand Tree", "Tree Gnome Village"}, null, null),
            GuideStep.optionalQuest("legends", "Legends' Quest", "Legends' Guild",
                    "Cape of legends, guild",
                    new String[]{"Family Crest", "Heroes' Quest", "Shilo Village", "Underground Pass", "Waterfall Quest"},
                    new int[][]{{AGIL, 50}, {CRAFT, 50}, {HERB, 45}, {MAG, 56}, {MINE, 52}, {PRAY, 42}, {SMTH, 50}, {STR, 50}, {THIE, 50}, {WC, 50}}, null),

            GuideStep.optionalQuest("lunar", "Lunar Diplomacy", "Lokar, Rellekka dock",
                    "Lunar spellbook",
                    new String[]{"The Fremennik Trials", "Lost City", "Rune Mysteries", "Shilo Village"},
                    new int[][]{{CRAFT, 61}, {DEF, 40}, {FM, 49}, {HERB, 5}, {MAG, 65}, {MINE, 60}, {WC, 55}}, null),
            GuideStep.optionalQuest("dream", "Dream Mentor", "Fallen man, Lunar Isle",
                    "Extra lunar spells",
                    new String[]{"Lunar Diplomacy", "Eadgar's Ruse"}, new int[][]{{HP, 85}}, null),
            GuideStep.optionalQuest("kings-ransom", "King's Ransom", "Gossip, Sinclair Mansion",
                    "Then Knight Waves for Chivalry/Piety",
                    new String[]{"Black Knights' Fortress", "Holy Grail", "Murder Mystery", "One Small Favour"},
                    new int[][]{{MAG, 45}, {DEF, 65}}, null),

            GuideStep.optionalQuest("smoking", "Smoking Kills", "Sumona, Pollnivneach",
                    "Slayer point shop + slayer helm",
                    new String[]{"Icthlarin's Little Helper", "The Restless Ghost"},
                    new int[][]{{SLAY, 35}, {CRAFT, 25}}, null),
            GuideStep.optionalQuest("all-fired", "All Fired Up", "King Roald, Varrock palace",
                    "Beacon minigame — ring/gloves/adze",
                    new String[]{"Priest in Peril"}, new int[][]{{FM, 43}}, null),
            GuideStep.optionalQuest("wgs", "While Guthix Sleeps", "Ivy Sophista / Movario",
                    "Tormented demons — only if implemented",
                    null, null, null),
    };

    private OptimalRoute() {
    }
}